In [3]:
import itertools
import json
import numpy as np
import torch
from progress.bar import Bar
from ga import GA

from preprocess import load_tensors, phi


seed = 12345324
np.random.seed(seed)
torch.random.manual_seed(seed)

### PSO Hyperparameters
pso_epochs = 2000
inertia = 0.1
a1 = 1.1
a2 = 2.9
population_size = 30
search_range = 10

### GA Hyperparameters
max_hidden_units = 10

D_range = [3,4,5,6]
N_range = [200,400,600,800,1000]
T_range = [10, 100, 250, 500]
p_m_range = np.logspace(-5, -1)
p_c_range = np.arange(0, 1, 0.2)


x_train, y_train, x_val, y_val, x_test, y_test = load_tensors('/home/mclancy/Documents/notes/edinburgh/year4/naturalcomputing/coursework/data/two_spirals.dat')


param_combinations = itertools.product(D_range, N_range, T_range, p_m_range, p_c_range)
bar = Bar('Hyperparameter set', max=len(param_combinations))


for params in param_combinations:
    D = params[0]
    N = params[1]
    T = params[2]
    p_m = params[3]
    p_c = params[4]
    GA_ = GA(x_train=x_train, y_train=y_train,
             x_val=x_val, y_val=y_val,
             D=D, N=N,
             T=T, p_c=p_c, p_m=p_m, seed=seed, max_hidden_units = max_hidden_units,
             inertia=inertia, a1=a1, a2=a2, population_size=population_size,
             search_range=search_range, phi=phi)

    best_network_structure, validation_loss, validation_accuracy = GA_.run(pso_epochs)

    print(f" Validation Loss={validation_loss}")
    if validation_loss < best_validation_loss:
        best_D = D
        best_N = N
        best_T = T
        best_p_m = p_m
        best_p_c = p_c
        best_validation_loss = validation_loss

    bar.next()

with open("data/hyperparamsearch/bestparams.json", 'w') as fp:
    json.dump({"D": best_D, "N": best_N, "T": best_T, "p_m": best_p_m, "p_c": best_p_c, "validation_loss": best_validation_loss}, fp)

Currently training: [3. 0. 1.].
Loaded from disk.
[3. 0. 1.] with fitness 1999    tensor(0.7762, requires_grad=True)
Name: (val, fitness), dtype: object.
Currently training: [5. 5. 1.].
[5. 5. 1.] with fitness 1999    tensor(28.3220, grad_fn=<BinaryCrossEntropyWit...
Name: (val, fitness), dtype: object.
Currently training: [4. 2. 1.].
[4. 2. 1.] with fitness 1999    tensor(0.7586, grad_fn=<BinaryCrossEntropyWith...
Name: (val, fitness), dtype: object.
Currently training: [2. 1. 1.].
[2. 1. 1.] with fitness 1999    tensor(0.6672, grad_fn=<BinaryCrossEntropyWith...
Name: (val, fitness), dtype: object.
Currently training: [3. 6. 1.].
[3. 6. 1.] with fitness 1999    tensor(0.5786, grad_fn=<BinaryCrossEntropyWith...
Name: (val, fitness), dtype: object.
Currently training: [3. 4. 1.].


/home/mclancy/.local/share/pyenv/versions/natcomp/lib/python3.8/site-packages/pandas/core/generic.py:2434: PerformanceWarning: 
your performance may suffer as PyTables will pickle object types that it cannot
map directly to c-types [inferred_type->mixed,key->block0_values] [items->Int64Index([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,
            ...
            1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999],
           dtype='int64', length=2000)]

  pytables.to_hdf(


KeyboardInterrupt: 

In [7]:
D = 3
N = 200
T = 1
p_m = 0.03
p_c = 0.7

GA_ = GA(x_train=x_train, y_train=y_train,
         x_val=x_val, y_val=y_val,
         D=D, N=N,
         T=T, p_c=p_c, p_m=p_m, seed=seed, max_hidden_units = 2,
         inertia=inertia, a1=a1, a2=a2, population_size=population_size,
         search_range=search_range, phi=phi)
GA_.run(1)




Currently training: [2. 0. 1.].
Loaded from disk.
[2. 0. 1.] with fitness 0    tensor(0.9733, requires_grad=True)
Name: (val, fitness), dtype: object.
Currently training: [3. 0. 1.].
Loaded from disk.
[3. 0. 1.] with fitness 0    tensor(0.7840, requires_grad=True)
Name: (val, fitness), dtype: object.
Currently training: [5. 1. 1.].
Loaded from disk.
[5. 1. 1.] with fitness 0    tensor(0.8047, requires_grad=True)
Name: (val, fitness), dtype: object.
Currently training: [4. 0. 1.].
Loaded from disk.
[4. 0. 1.] with fitness 0    tensor(0.7202, requires_grad=True)
Name: (val, fitness), dtype: object.
Currently training: [4. 0. 1.].
Loaded from disk.
[4. 0. 1.] with fitness 0    tensor(0.7202, requires_grad=True)
Name: (val, fitness), dtype: object.
Currently training: [5. 1. 1.].
Loaded from disk.
[5. 1. 1.] with fitness 0    tensor(0.8047, requires_grad=True)
Name: (val, fitness), dtype: object.
Currently training: [5. 1. 1.].
Loaded from disk.
[5. 1. 1.] with fitness 0    tensor(0.8047, 

(array([3., 1., 1.]), 0.693859875202179)