In [1]:
import numpy as np
import torch
from torch import nn
from psopy.ga import GA

from psopy.models import BaselineSpiralClassifier
from psopy.optimization import PSO
from psopy.preprocess import load_tensors, phi

from psopy.training import TrainingInstance

seed = 12345324
np.random.seed(seed)
torch.random.manual_seed(seed)

### PSO Hyperparameters
epochs = 1000
inertia = 0.7
a1 = 1.4
a2 = 1.8
population_size = 30
search_range = 1

### GA Hyperparameters
D = 8
N = 30
T = 10
p_c=0.7
p_m = 0.01
max_hidden_units = 10

x_train, y_train, x_val, y_val, x_test, y_test = load_tensors('/home/mclancy/Documents/notes/edinburgh/year4/naturalcomputing/coursework/data/two_spirals.dat')

GA_ = GA(x_train=x_train, y_train=y_train,
         D=D, N=N,
         T=T, p_c=p_c, p_m=p_m, seed=seed, max_hidden_units = max_hidden_units,
         inertia=inertia, a1=a1, a2=a2, population_size=population_size,
         search_range=search_range, phi=phi)

GA_.run(1000)

Currently training: [3. 2. 3. 2. 8. 4. 1. 1.].
[3. 2. 3. 2. 8. 4. 1. 1.] with fitness 999    tensor(0.6424, grad_fn=<BinaryCrossEntropyWith...
Name: (train, fitness), dtype: object.
Currently training: [5. 1. 1. 2. 6. 2. 7. 1.].
[5. 1. 1. 2. 6. 2. 7. 1.] with fitness 999    tensor(0.6606, grad_fn=<BinaryCrossEntropyWith...
Name: (train, fitness), dtype: object.
Currently training: [4. 6. 7. 3. 1. 6. 8. 1.].
[4. 6. 7. 3. 1. 6. 8. 1.] with fitness 999    tensor(0.4072, grad_fn=<BinaryCrossEntropyWith...
Name: (train, fitness), dtype: object.
Currently training: [2. 4. 5. 6. 5. 3. 9. 1.].
[2. 4. 5. 6. 5. 3. 9. 1.] with fitness 999    tensor(0.5430, grad_fn=<BinaryCrossEntropyWith...
Name: (train, fitness), dtype: object.
Currently training: [3. 4. 8. 9. 6. 1. 0. 1.].
[3. 4. 8. 9. 6. 1. 0. 1.] with fitness 999    tensor(0.5487, grad_fn=<BinaryCrossEntropyWith...
Name: (train, fitness), dtype: object.
Currently training: [3. 6. 3. 5. 2. 9. 9. 1.].
[3. 6. 3. 5. 2. 9. 9. 1.] with fitness 999 

/home/mclancy/.local/share/pyenv/versions/natcomp/lib/python3.8/site-packages/pandas/core/generic.py:2434: PerformanceWarning: 
your performance may suffer as PyTables will pickle object types that it cannot
map directly to c-types [inferred_type->mixed,key->block0_values] [items->Int64Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
            ...
            990, 991, 992, 993, 994, 995, 996, 997, 998, 999],
           dtype='int64', length=1000)]

  pytables.to_hdf(


In [2]:
GA_.roulette_wheel_selection(sorted_pop, fitness_list)

NameError: name 'sorted_pop' is not defined

In [ ]:
GA_ = GA(3, 10, 100, 0.7, 0.01)
GA_.run(10000)